export const dataHeader = [
  "localidad",
  "ma_ef",
  "ma_em",
  "ma_af",
  "ma_am",
  "ma_jf",
  "ma_jm",
  "mna_ef",
  "mna_em",
  "mna_af",
  "mna_am",
  "mna_jf",
  "mna_jm",
  "eq_ef",
  "eq_em",
  "eq_af",
  "eq_am",
  "eq_jf",
  "eq_jm",
  "form_ef",
  "form_em",
  "form_af",
  "form_am",
  "form_jf",
  "form_jm",
  "paso_ef",
  "paso_em",
  "paso_jf",
  "paso_jm",
  "colab_f",
  "colab_m",
  "disc_f",
  "disc_m",
  "eqm_f",
  "eqm_m",
  "mis_f",
  "mis_m",
  "prom_f",
  "prom_m",
  "sac_dic",
  "sec_resp",
  "fecha",
  "trimestre",
];

export const localidades = [
  "Acapulco",
  "Campeche",
  "Cancún",
  "Chetumal",
  "Costa Rica",
  "Cotija",
  "Cozumel",
  "Cuernavaca",
  "Córdoba",
  "El Salvador",
  "Guatemala",
  "Lindavista",
  "Morelia",
  "Mérida",
  "México Norte",
  "México Poniente",
  "México Sur",
  "Oaxaca",
  "Orizaba",
  "Pachuca",
  "Playa del Carmen",
  "Puebla",
  "Querétaro",
  "Tapachula",
  "Toluca",
  "Tuxtla Gutiérrez",
  "Veracruz",
  "Villahermosa",
  "Xalapa",
];

export const localidadesG = [...localidades, "Territorial"];

export const nombreSecciones = [
  "ECYD Femenino",
  "ECYD Masculino",
  "Jóvenes Femenino",
  "Jóvenes Masculino",
  "Adultos Femenino",
  "Adultos Masculino",
];

export const traductorSecciones = {
  "Adultos Femenino": "af",
  "Adultos Masculino": "am",
  "Jóvenes Femenino": "jf",
  "Jóvenes Masculino": "jm",
  "ECYD Femenino": "ef",
  "ECYD Masculino": "em",
};

export const traductorAbrebiaciones = {
  af: "Adultos Femenino",
  am: "Adultos Masculino",
  jf: "Jóvenes Femenino",
  jm: "Jóvenes Masculino",
  ef: "ECYD Femenino",
  em: "ECYD Masculino",
};
